language: node_js
node_js:
  - "4.1"
  - "4.0"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - sudo apt-get -qq install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential
env:
  - CXX=g++-4.8
